### ISSUE TITLE
how culli store is different from stanga?

### ISSUE THREAD

**Issue by sampleapp** [milankinen/culli#10]

**Comment by milankinen** [comment]
Hi @sampleapp!

`@culli/store` is basically just a successor of Stanga, with Cycle Diversity support and some performance optimizations. 

The biggest difference is that in `stanga`, you must use `.set` and `.modify` to directly modify store's state, whereas in `@culli/store` you must define state changes with `actions.reduce => dispatch` and use the `dispatch` in place of `set/modify`.

**Comment by sampleapp** [comment]
Thanks, it helps, "Successor of Stanga".
